[package]
name = "raytracer_from_scratch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_math = "0.11.3"
image = "0.24.7"
tracing = "0.1.37"
